class Asset {
  static const String path = "assets/icons",
      logo = "$path/logo.png",
      logo1 = "$path/logo1.png",
      admin = "$path/Admin.png",
      emailIcon = "$path/email.svg",
      passwordIcon = "$path/password.svg",
      showPass = "$path/showPass.svg",
      code = "$path/code.svg",
      out = "$path/out.svg",
      boxes = "$path/boxes.svg",
      course = "$path/course.svg",
      create = "$path/create.svg",
      search = "$path/search.svg",
      boxx = "$path/boxx.svg",
      home = "$path/home.svg",
      profile = "$path/profile.svg",
      notif = "$path/bell.svg",
      id = "$path/id.svg",
      codez = "$path/codez.svg",
      person = "$path/person.svg",
      add = "$path/add.svg",
      pen = "$path/pen.svg",
      phone = "$path/phone.svg",
      warning = "$path/warning.png",
      back = "$path/back.svg",
      success = "$path/tick.png",
      lock = "$path/lock.svg",
      hidePass = "$path/hidePass.svg";
}
// PostgrestException 
// AuthException