name: rpcadvisorapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.3
  go_router: ^14.2.7
  intl: ^0.19.0
  badges: ^3.0.2
  supabase_flutter: ^2.6.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.10+1
  dropdown_search: ^5.0.5
  enhanced_read_more: ^0.0.2
  firebase_messaging: ^14.2.4
  firebase_core: ^2.6.1
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.0.17
  dio: ^5.0.0
  syncfusion_flutter_signaturepad: ^26.2.11
  path_provider: ^2.0.13
  cr_file_saver: ^0.0.2+1
  printing: ^5.11.0
  syncfusion_flutter_pdfviewer: ^26.2.11
  permission_handler: ^11.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_icons:
  android: "logo_square"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: GeneralSansRegular
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
    - family: GeneralSansMedium
      fonts:
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500 
    - family: GeneralSansSemiBold
      fonts:
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600 
    - family: GeneralSansBold
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.otf     
          weight: 700       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
