// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07fiwpykb19vPU-PCpcuo_XlP0eXtw7g',
    appId: '1:656027163077:android:9fd08c23896cfc796d93ac',
    messagingSenderId: '656027163077',
    projectId: 'rpc2023-5ad2e',
    storageBucket: 'rpc2023-5ad2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6n38quenTuOyNcFWo4VBFtZaEuI8OJU',
    appId: '1:656027163077:ios:3ca049ee0c51cc1e6d93ac',
    messagingSenderId: '656027163077',
    projectId: 'rpc2023-5ad2e',
    storageBucket: 'rpc2023-5ad2e.appspot.com',
    androidClientId: '656027163077-m74ktags542n8ohite62bauombiq6e7n.apps.googleusercontent.com',
    iosBundleId: 'app.rpcUMTeachers.rpcadvisorapp',
  );
}
